l_english:
 SETTING_AUTOSAVE:0 "Częstotliwość autozapisu"
 SETTING_DEBUG_SAVES:0 "Liczba debugowanych zapisów"
 SETTING_TUTORIAL:0 "Samouczek"
 SETTING_DISABLED_HINTS:0 "Wyłączone wskazówki"
 SETTING_FOCUS_ON_COMBAT:0 "Zbliżenie na walkę"
 SETTING_TOOLTIP_DELAY:0 "Opóźnienie wskazówki"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_TOOLTIP_DELAY$#!\nOkreśla opóźnienie przed pojawieniem się podpowiedzi."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Czas odblokowania"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nOkreśla czas po jakim wskazówka będzie odblokowana."
 SETTING_TOOLTIP_LOCK_TIME:0 "Czas zablokowania"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nOkreśla czas po jakim wskazówka zostanie zablokowana."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Czas zablokowania otwartej"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nOkreśla czas po jakim wskazówka zostanie zablokowana jeśli inna wskazówka jest już otwarta."
 SETTING_Sound_Effects:0 "Wszystkie efekty dźwiękowe"
 SETTING_Sound_Effects_TOOLTIP:0 "#T Głośność efektów dźwiękowych\n#!Określa głośność WSZYSTKICH efektów dźwiękowych."
 SETTING_Ambience:0 "Otoczenie"
 SETTING_Ambience_TOOLTIP:0 "#T Głośność otoczenia\n#!Określa poziom głośności efektów otoczenia."
 SETTING_TOOLTIP_MODE:0 "Tryb wskazówek"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE$#!\nUstawia sposób, w jaki podpowiedzi "blokują się", włączając podpowiedzi w podpowiedziach."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Obecność myszy"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nWskazówka automatycznie blokuje się na miejscu dopóki kursor się nie odsunie."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Blokada akcją"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nNaciśnij #V środkowy przycisk myszy#! aby zablokować i odblokować wskazówki."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Blokada czasowa"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nJeśli kursor przez chwilę jest nieruchomy to wskazówki są blokowane. #weak (Ustawienie domyślne)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Różne"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Podpowiedzi"
 SETTINGS_CATEGORY_SFX:0 "Efekty dźwiękowe"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Ogólne"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Kontrola mapy"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Zapisane gry"
 SETTINGS_CATEGORY_LANGUAGE:0 "Język"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Zaawansowane"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portrety"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Pokaż choroby i urazy na portretach"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nOkreśla, czy urazy i choroby będą widoczne na portretach postaci."
 SETTING_SHOW_NUDITY:0 "Pokaż nagość"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nOkreśla, czy postacie mogą być pokazywane nago."
 NEVER:0 "Nigdy"
 MONTHLY:0 "Co miesiąc"
 HALFYEAR:0 "Co 6 miesięcy"
 YEARLY:0 "Co roku"
 FIVE_YEAR:0 "Co 5 lat"
 SETTINGS_CATEGORY_TUTORIAL:0 "Samouczek"
 SETTING_REACTIVE_TUTORIAL:0 "Pokaż reaktywną poradę"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nUstawia, czy gra będzie wyświetlała porady w stylu samouczka w reakcji na twoje działania. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Pokazuj sugestie"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:0 "#T $SETTING_SHOW_SUGGESTIONS$#!\nUstawia, czy gra ma wyświetlać sugestie w określonych odstępach czasu. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_TOOLTIP:0 "#T Zresetuj reaktywną poradę#!\nWcześniej widziane porady reaktywne pojawią się ponownie."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Czy na pewno chcesz zresetować reaktywną poradę?"
 SETTING_ADVANCED_SHADERS:0 "Zaawansowane efekty shaderów"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Zaawansowane efekty cieni#!\nTa opcja włącza zaawansowane efekty cieniowania. Wyłączenie jej może zwiększyć wydajność kosztem pogorszenia wyglądu niektórych efektów (np. terenu i wody)"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Winter Particle Effects"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermines whether particle effects are shown or not when Winter is active in some areas of the map.\n\nTurning it off may increase performance"
 BASED_ON_ZOOM_LEVEL:0 "Dynamiczne"
 ALWAYS_HIDE:0 "Zawsze ukryte"
 ALWAYS_SHOW:0 "Zawsze widoczne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Granice przybrzeżne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nTa opcja pozwoli kontrolować, kiedy powinny zostać pokazane granice morskie.\nJeśli ustawienie jest $BASED_ON_ZOOM_LEVEL$, zostaną one ukryte w przybliżeniu.\n\nWybranie $ALWAYS_SHOW$ lub $ALWAYS_HIDE$ może zwiększyć wydajność kosztem dynamicznego pojawiania granic przybrzeżnych."
